/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasswordResetRouteRouteImport } from './routes/_password-reset/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as LegalRouteRouteImport } from './routes/_legal/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasswordResetResetPasswordRouteImport } from './routes/_password-reset/reset-password'
import { Route as PasswordResetForgotPasswordRouteImport } from './routes/_password-reset/forgot-password'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as LegalTermsRouteImport } from './routes/_legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/_legal/privacy'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PasswordResetRouteRoute = PasswordResetRouteRouteImport.update({
  id: '/_password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetResetPasswordRoute =
  PasswordResetResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => PasswordResetRouteRoute,
  } as any)
const PasswordResetForgotPasswordRoute =
  PasswordResetForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => PasswordResetRouteRoute,
  } as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/dashboard': typeof MainDashboardRoute
  '/forgot-password': typeof PasswordResetForgotPasswordRoute
  '/reset-password': typeof PasswordResetResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/dashboard': typeof MainDashboardRoute
  '/forgot-password': typeof PasswordResetForgotPasswordRoute
  '/reset-password': typeof PasswordResetResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_legal': typeof LegalRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_password-reset': typeof PasswordResetRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_legal/privacy': typeof LegalPrivacyRoute
  '/_legal/terms': typeof LegalTermsRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_password-reset/forgot-password': typeof PasswordResetForgotPasswordRoute
  '/_password-reset/reset-password': typeof PasswordResetResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_legal'
    | '/_main'
    | '/_password-reset'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_legal/privacy'
    | '/_legal/terms'
    | '/_main/dashboard'
    | '/_password-reset/forgot-password'
    | '/_password-reset/reset-password'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  PasswordResetRouteRoute: typeof PasswordResetRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_password-reset': {
      id: '/_password-reset'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PasswordResetRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_password-reset/reset-password': {
      id: '/_password-reset/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PasswordResetResetPasswordRouteImport
      parentRoute: typeof PasswordResetRouteRoute
    }
    '/_password-reset/forgot-password': {
      id: '/_password-reset/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PasswordResetForgotPasswordRouteImport
      parentRoute: typeof PasswordResetRouteRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_legal/terms': {
      id: '/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_legal/privacy': {
      id: '/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface LegalRouteRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainDashboardRoute: typeof MainDashboardRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainDashboardRoute: MainDashboardRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface PasswordResetRouteRouteChildren {
  PasswordResetForgotPasswordRoute: typeof PasswordResetForgotPasswordRoute
  PasswordResetResetPasswordRoute: typeof PasswordResetResetPasswordRoute
}

const PasswordResetRouteRouteChildren: PasswordResetRouteRouteChildren = {
  PasswordResetForgotPasswordRoute: PasswordResetForgotPasswordRoute,
  PasswordResetResetPasswordRoute: PasswordResetResetPasswordRoute,
}

const PasswordResetRouteRouteWithChildren =
  PasswordResetRouteRoute._addFileChildren(PasswordResetRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  PasswordResetRouteRoute: PasswordResetRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
